image: jelaniwoods/appdev2022-base-exercism

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
